name: Wrapper Release

on:
  workflow_call:
    inputs:
      username:
        description: 'wrapper'
        default: 'python'
        required: false
        type: string

jobs:
  envs:
    name: Gather release environments
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.env_matrix.outputs.matrix}}
      
    steps:
      - id: env_matrix
        run: echo "::set-output name=matrix::$(curl --silent 'https://downloadshaw2eefaey.blob.core.windows.net/envs/envs.json' | jq  -c )"
